backend:
  name: webriq-api #netlify-api
  repo: webriq/webriqpage-flymycommunity-landing2 # Updated repo details ### Original: owner/repo
  branch: master

production:
  backend:
    name: webriq-api
    repo: webriq/webriqpage-flymycommunity-landing2 # Updated repo details ### Original: owner/repo # Path to your Github repository
    branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go
public_folder: "assets"

responsive_images: true

collections: # A list of collections the CMS should be able to edit
  - name: "sitedata"
    label: "Site Information"
    create: true
    files:
      - name: "sitedata"
        label: "Site Information"
        file: "data/site.json"
        description: "edit site setting"
        fields:
          - label: "Site Information"
            name: "sitedata"
            widget: "list"
            fields:
              - {label: "Website Title", name: "sitename", widget: "string"}
              - {label: "Website Meta Description", name: "metadesc", widget: "string"}
              - {label: "Website Meta Keywords", name: "metakeyword", widget: "string"}
              - {label: "Website Author", name: "metauthor", widget: "string"}
              - {label: "Website Logo", name: "logo", widget: "image", media_folder: "assets/img", dom_data: [{ target: ".logohere img", attr: "src"}]}
          - label: "Content Information"
            name: "content"
            widget: "list"
            fields:
              - {label: "Your Email", name: "email", widget: "string", dom_data: [{ target: ".mail a", attr: "mailto" }, { target: ".mail a span", attr: "text" }]}
              - {label: "Your Contact Phone Number", name: "linkcont", widget: "string", dom_data: [{target: ".phone a", attr: "href"}, {target: ".phone a span", attr: "text"}]}
              - {label: "Video ID", "name": "videoid", widget: "string", dom_data: [{ target: ".videohere iframe", attr: "src", value_pattern: "https://player.vimeo.com/video/{0}?background=1" }]}
          - label: "About Information"
            name: "about"
            widget: "list"
            fields:
              - {label: "Video Title", name: "abouttext1", placeholder_text: "Edit video title", default_text: "Crystal Park - FMC ", widget: "string", dom_data: [{ target: ".video-title", attr: "text"}]}
              - {label: "Video Description", name: "abouttext2", placeholder_text: "Edit video description", default_text: "Crystal Park is a private gated mountain community within the Pikes Peak region. Located above Colorado Springs and adjacent to Manitou Springs.....", widget: "string", dom_data: [{ target: ".video-description", attr: "text"}]}
